// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type DailyTextCreate = {
    middah: string;
    sefaria_url: (string | null);
    title: (string | null);
    content: (string | null);
};

export type DailyTextPatch = {
    middah?: (string | null);
    sefaria_url?: (string | null);
    title?: (string | null);
    content?: (string | null);
};

export type DailyTextRead = {
    middah: string;
    sefaria_url: (string | null);
    title: (string | null);
    content: (string | null);
    id: number;
    created_at: string;
    updated_at: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type KabbalahCreate = {
    middah: string;
    description: string;
};

export type KabbalahPatch = {
    middah?: (string | null);
    description?: (string | null);
};

export type KabbalahRead = {
    middah: string;
    description: string;
    id: number;
    created_at: string;
    updated_at: string;
};

export type Message = {
    message: string;
};

export type MiddahCreate = {
    name_transliterated: string;
    name_hebrew: string;
    name_english: string;
};

export type MiddahRead = {
    name_transliterated: string;
    name_hebrew: string;
    name_english: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ReminderPhraseCreate = {
    middah: string;
    text: string;
};

export type ReminderPhrasePatch = {
    middah?: (string | null);
    text?: (string | null);
};

export type ReminderPhraseRead = {
    middah: string;
    text: string;
    id: number;
    created_at: string;
    updated_at: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type WeeklyTextCreate = {
    sefaria_url: (string | null);
    title: (string | null);
    content: (string | null);
};

export type WeeklyTextPatch = {
    sefaria_url?: (string | null);
    title?: (string | null);
    content?: (string | null);
};

export type WeeklyTextRead = {
    sefaria_url: (string | null);
    title: (string | null);
    content: (string | null);
    id: number;
    created_at: string;
    updated_at: string;
};

export type DailyTextsListDailyTextsResponse = (Array<DailyTextRead>);

export type DailyTextsCreateDailyTextData = {
    requestBody: DailyTextCreate;
};

export type DailyTextsCreateDailyTextResponse = (DailyTextRead);

export type DailyTextsGetDailyTextData = {
    id: number;
};

export type DailyTextsGetDailyTextResponse = (DailyTextRead);

export type DailyTextsPatchDailyTextData = {
    id: number;
    requestBody: DailyTextPatch;
};

export type DailyTextsPatchDailyTextResponse = (DailyTextRead);

export type DailyTextsDeleteDailyTextData = {
    id: number;
};

export type DailyTextsDeleteDailyTextResponse = (void);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type KabbalotListKabbalotResponse = (Array<KabbalahRead>);

export type KabbalotCreateKabbalahData = {
    requestBody: KabbalahCreate;
};

export type KabbalotCreateKabbalahResponse = (KabbalahRead);

export type KabbalotGetKabbalahData = {
    id: number;
};

export type KabbalotGetKabbalahResponse = (KabbalahRead);

export type KabbalotPatchKabbalahData = {
    id: number;
    requestBody: KabbalahPatch;
};

export type KabbalotPatchKabbalahResponse = (KabbalahRead);

export type KabbalotDeleteKabbalahData = {
    id: number;
};

export type KabbalotDeleteKabbalahResponse = (void);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MiddotListMiddotResponse = (Array<MiddahRead>);

export type MiddotCreateMiddahData = {
    requestBody: MiddahCreate;
};

export type MiddotCreateMiddahResponse = (MiddahRead);

export type MiddotGetMiddahData = {
    nameTransliterated: string;
};

export type MiddotGetMiddahResponse = (MiddahRead);

export type MiddotDeleteMiddahData = {
    nameTransliterated: string;
};

export type MiddotDeleteMiddahResponse = (void);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ReminderPhrasesListReminderPhrasesResponse = (Array<ReminderPhraseRead>);

export type ReminderPhrasesCreateReminderPhraseData = {
    requestBody: ReminderPhraseCreate;
};

export type ReminderPhrasesCreateReminderPhraseResponse = (ReminderPhraseRead);

export type ReminderPhrasesGetReminderPhraseData = {
    id: number;
};

export type ReminderPhrasesGetReminderPhraseResponse = (ReminderPhraseRead);

export type ReminderPhrasesPatchReminderPhraseData = {
    id: number;
    requestBody: ReminderPhrasePatch;
};

export type ReminderPhrasesPatchReminderPhraseResponse = (ReminderPhraseRead);

export type ReminderPhrasesDeleteReminderPhraseData = {
    id: number;
};

export type ReminderPhrasesDeleteReminderPhraseResponse = (void);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type WeeklyTextsListWeeklyTextsResponse = (Array<WeeklyTextRead>);

export type WeeklyTextsCreateWeeklyTextData = {
    requestBody: WeeklyTextCreate;
};

export type WeeklyTextsCreateWeeklyTextResponse = (WeeklyTextRead);

export type WeeklyTextsGetWeeklyTextData = {
    id: number;
};

export type WeeklyTextsGetWeeklyTextResponse = (WeeklyTextRead);

export type WeeklyTextsPatchWeeklyTextData = {
    id: number;
    requestBody: WeeklyTextPatch;
};

export type WeeklyTextsPatchWeeklyTextResponse = (WeeklyTextRead);

export type WeeklyTextsDeleteWeeklyTextData = {
    id: number;
};

export type WeeklyTextsDeleteWeeklyTextResponse = (void);