/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutWeeklyTextsRouteImport } from './routes/_layout/weekly-texts'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutReminderPhrasesRouteImport } from './routes/_layout/reminder-phrases'
import { Route as LayoutMiddotRouteImport } from './routes/_layout/middot'
import { Route as LayoutKabbalotRouteImport } from './routes/_layout/kabbalot'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutDailyTextsRouteImport } from './routes/_layout/daily-texts'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWeeklyTextsRoute = LayoutWeeklyTextsRouteImport.update({
  id: '/weekly-texts',
  path: '/weekly-texts',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReminderPhrasesRoute = LayoutReminderPhrasesRouteImport.update({
  id: '/reminder-phrases',
  path: '/reminder-phrases',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMiddotRoute = LayoutMiddotRouteImport.update({
  id: '/middot',
  path: '/middot',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutKabbalotRoute = LayoutKabbalotRouteImport.update({
  id: '/kabbalot',
  path: '/kabbalot',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDailyTextsRoute = LayoutDailyTextsRouteImport.update({
  id: '/daily-texts',
  path: '/daily-texts',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/daily-texts': typeof LayoutDailyTextsRoute
  '/items': typeof LayoutItemsRoute
  '/kabbalot': typeof LayoutKabbalotRoute
  '/middot': typeof LayoutMiddotRoute
  '/reminder-phrases': typeof LayoutReminderPhrasesRoute
  '/settings': typeof LayoutSettingsRoute
  '/weekly-texts': typeof LayoutWeeklyTextsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/daily-texts': typeof LayoutDailyTextsRoute
  '/items': typeof LayoutItemsRoute
  '/kabbalot': typeof LayoutKabbalotRoute
  '/middot': typeof LayoutMiddotRoute
  '/reminder-phrases': typeof LayoutReminderPhrasesRoute
  '/settings': typeof LayoutSettingsRoute
  '/weekly-texts': typeof LayoutWeeklyTextsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/daily-texts': typeof LayoutDailyTextsRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/kabbalot': typeof LayoutKabbalotRoute
  '/_layout/middot': typeof LayoutMiddotRoute
  '/_layout/reminder-phrases': typeof LayoutReminderPhrasesRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/weekly-texts': typeof LayoutWeeklyTextsRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/daily-texts'
    | '/items'
    | '/kabbalot'
    | '/middot'
    | '/reminder-phrases'
    | '/settings'
    | '/weekly-texts'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/daily-texts'
    | '/items'
    | '/kabbalot'
    | '/middot'
    | '/reminder-phrases'
    | '/settings'
    | '/weekly-texts'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/daily-texts'
    | '/_layout/items'
    | '/_layout/kabbalot'
    | '/_layout/middot'
    | '/_layout/reminder-phrases'
    | '/_layout/settings'
    | '/_layout/weekly-texts'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/weekly-texts': {
      id: '/_layout/weekly-texts'
      path: '/weekly-texts'
      fullPath: '/weekly-texts'
      preLoaderRoute: typeof LayoutWeeklyTextsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/reminder-phrases': {
      id: '/_layout/reminder-phrases'
      path: '/reminder-phrases'
      fullPath: '/reminder-phrases'
      preLoaderRoute: typeof LayoutReminderPhrasesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/middot': {
      id: '/_layout/middot'
      path: '/middot'
      fullPath: '/middot'
      preLoaderRoute: typeof LayoutMiddotRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/kabbalot': {
      id: '/_layout/kabbalot'
      path: '/kabbalot'
      fullPath: '/kabbalot'
      preLoaderRoute: typeof LayoutKabbalotRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/daily-texts': {
      id: '/_layout/daily-texts'
      path: '/daily-texts'
      fullPath: '/daily-texts'
      preLoaderRoute: typeof LayoutDailyTextsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutDailyTextsRoute: typeof LayoutDailyTextsRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutKabbalotRoute: typeof LayoutKabbalotRoute
  LayoutMiddotRoute: typeof LayoutMiddotRoute
  LayoutReminderPhrasesRoute: typeof LayoutReminderPhrasesRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutWeeklyTextsRoute: typeof LayoutWeeklyTextsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutDailyTextsRoute: LayoutDailyTextsRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutKabbalotRoute: LayoutKabbalotRoute,
  LayoutMiddotRoute: LayoutMiddotRoute,
  LayoutReminderPhrasesRoute: LayoutReminderPhrasesRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutWeeklyTextsRoute: LayoutWeeklyTextsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
